INSERT INTO BOOK(ID, TITLE, AUTHOR, STOCK_COUNT, PRICE) VALUES
(1, 'Suc Ve Ceza', 'Dostoyevski', 30, 43);

INSERT INTO BOOK(ID, TITLE, AUTHOR, STOCK_COUNT, PRICE) VALUES
(2, 'Yasli Adam ve Deniz', 'Hemingway', 10, 22);

INSERT INTO BOOK(ID, TITLE, AUTHOR, STOCK_COUNT, PRICE) VALUES
(3, 'Zorba', 'Kazancakis', 1, 52);

INSERT INTO CUSTOMER(ID, CUSTOMER_NO, NAME) VALUES
(1, '1', 'HAKAN ARAYICI');

INSERT INTO CUSTOMER_ORDER(ID, CUSTOMER_ID,CREATE_DATE) VALUES
(1, 1, TIMESTAMP '2022-01-23 00:00:00');

INSERT INTO CUSTOMER_ORDER(ID, CUSTOMER_ID,CREATE_DATE) VALUES
(2, 1, TIMESTAMP '2022-02-20 00:00:00');

INSERT INTO ORDER_BOOK(ID, ORDER_ID, BOOK_ID, QUANTITY) VALUES
(1,1,1,1);

INSERT INTO ORDER_BOOK(ID, ORDER_ID, BOOK_ID, QUANTITY) VALUES
(2,1,2,2);

INSERT INTO ORDER_BOOK(ID, ORDER_ID, BOOK_ID, QUANTITY) VALUES
(3,2,3,1);