CREATE MEMORY TABLE PUBLIC.BOOK(
    ID BIGINT NOT NULL,
    TITLE VARCHAR(255),
    AUTHOR VARCHAR(255),
    STOCK_COUNT INTEGER,
    PRICE NUMERIC
);
ALTER TABLE PUBLIC.BOOK ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);


CREATE MEMORY TABLE PUBLIC.CUSTOMER(
    ID BIGINT NOT NULL,
    NAME VARCHAR(50),
    CUSTOMER_NO VARCHAR(16)
);
ALTER TABLE PUBLIC.CUSTOMER ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID);

CREATE MEMORY TABLE PUBLIC."CUSTOMER_ORDER"(
    ID BIGINT NOT NULL,
    CUSTOMER_ID VARCHAR(50),
    CREATE_DATE TIMESTAMP
);
ALTER TABLE PUBLIC."CUSTOMER_ORDER" ADD CONSTRAINT PUBLIC.CONSTRAINT_10 PRIMARY KEY(ID);

CREATE MEMORY TABLE PUBLIC."ORDER_BOOK"(
    ID BIGINT NOT NULL,
    ORDER_ID BIGINT,
    BOOK_ID BIGINT,
    QUANTITY INTEGER
);
ALTER TABLE PUBLIC."ORDER_BOOK" ADD CONSTRAINT PUBLIC.CONSTRAINT_11 PRIMARY KEY(ID);

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 50 INCREMENT BY 1;